//Removes contractions from the variable 'text'
const contractionList = [
  { pattern: /\ba'ight\b/gi, replacement: "alright" },
  { pattern: /\bain't\b/gi, replacement: "is not" },
  { pattern: /\bamn't\b/gi, replacement: "am not" },
  { pattern: /\bn\b/gi, replacement: "and" },
  { pattern: /\barencha\b/gi, replacement: "are you not" },
  { pattern: /\baren't\b/gi, replacement: "are not" },
  { pattern: /\bbout\b/gi, replacement: "about" },
  { pattern: /\bcan't\b/gi, replacement: "can not" },
  { pattern: /\bcap'n\b/gi, replacement: "captain" },
  { pattern: /\bcause\b/gi, replacement: "because" },
  { pattern: /\bcuz\b/gi, replacement: "because" },
  { pattern: /\bcept\b/gi, replacement: "except" },
  { pattern: /\bc'mon\b/gi, replacement: "come on" },
  { pattern: /\bcould've\b/gi, replacement: "could have" },
  { pattern: /\bcouldn't\b/gi, replacement: "could not" },
  { pattern: /\bcouldn't've\b/gi, replacement: "could not have" },
  { pattern: /\bcuppa\b/gi, replacement: "cup of" },
  { pattern: /\bdaren't\b/gi, replacement: "dare not" },
  { pattern: /\bdaresn't\b/gi, replacement: "dare not" },
  { pattern: /\bdasn't\b/gi, replacement: "dare not" },
  { pattern: /\bdidn't\b/gi, replacement: "did not" },
  { pattern: /\bdoesn't\b/gi, replacement: "does not" },
  { pattern: /\bdon't\b/gi, replacement: "do not" },
  { pattern: /\bdunno\b/gi, replacement: "do not know" },
  { pattern: /\bd'ye\b/gi, replacement: "do you" },
  { pattern: /\bd'ya\b/gi, replacement: "do you" },
  { pattern: /\be'en\b/gi, replacement: "even" },
  { pattern: /\be'er\b/gi, replacement: "ever" },
  { pattern: /\bem\b/gi, replacement: "them" },
  { pattern: /\beverybody's\b/gi, replacement: "everybody has" },
  { pattern: /\beveryone's\b/gi, replacement: "everyone has" },
  { pattern: /\beverything's\b/gi, replacement: "everything has" },
  { pattern: /\bfinna\b/gi, replacement: "fixing to" },
  { pattern: /\bfo'c'sle\b/gi, replacement: "forecastle" },
  { pattern: /\bgainst\b/gi, replacement: "against" },
  { pattern: /\bg'day\b/gi, replacement: "good day" },
  { pattern: /\bgimme\b/gi, replacement: "give me" },
  { pattern: /\bgiv'n\b/gi, replacement: "given" },
  { pattern: /\bgi'z\b/gi, replacement: "give us" },
  { pattern: /\bgonna\b/gi, replacement: "going to" },
  { pattern: /\bgon't\b/gi, replacement: "go not" },
  { pattern: /\bgotta\b/gi, replacement: "got to" },
  { pattern: /\bhadn't\b/gi, replacement: "had not" },
  { pattern: /\bhad've\b/gi, replacement: "had have" },
  { pattern: /\bhasn't\b/gi, replacement: "has not" },
  { pattern: /\bhaven't\b/gi, replacement: "have not" },
  { pattern: /\bhe'd\b/gi, replacement: "he had" },
  { pattern: /\bhe'd'nt've\b/gi, replacement: "he did not have" },
  { pattern: /\bhe'll\b/gi, replacement: "he will" },
  { pattern: /\bhelluva\b/gi, replacement: "hell of a" },
  { pattern: /\byesn't\b/gi, replacement: "no" },
  { pattern: /\bhe's\b/gi, replacement: "he is" },
  { pattern: /\bhere's\b/gi, replacement: "here is" },
  { pattern: /\bhow'd\b/gi, replacement: "how did" },
  { pattern: /\bhowdy\b/gi, replacement: "how do you do" },
  { pattern: /\bhow'll\b/gi, replacement: "how will" },
  { pattern: /\bhow're\b/gi, replacement: "how are" },
  { pattern: /\bhow's\b/gi, replacement: "how is" },
  { pattern: /\bI'd\b/gi, replacement: "I would" },
  { pattern: /\bI'd've\b/gi, replacement: "I would have" },
  { pattern: /\bI'd'nt\b/gi, replacement: "I did not" },
  { pattern: /\bI'd'nt've\b/gi, replacement: "I did not have" },
  { pattern: /\bIf'n\b/gi, replacement: "If and when" },
  { pattern: /\bI'll\b/gi, replacement: "I will" },
  { pattern: /\bI'm\b/gi, replacement: "I am" },
  { pattern: /\bI'm'onna\b/gi, replacement: "I am going to" },
  { pattern: /\bImma\b/gi, replacement: "I am going to" },
  { pattern: /\bI'm'o\b/gi, replacement: "I am going to" },
  { pattern: /\bI'm'na\b/gi, replacement: "I am going to" },
  { pattern: /\binnit\b/gi, replacement: "is it not" },
  { pattern: /\bIon\b/gi, replacement: "I do not" },
  { pattern: /\bI've\b/gi, replacement: "I have" },
  { pattern: /\bisn't\b/gi, replacement: "is not" },
  { pattern: /\bit'd\b/gi, replacement: "it would" },
  { pattern: /\bit'll\b/gi, replacement: "it will" },
  { pattern: /\bit's\b/gi, replacement: "it is" },
  { pattern: /\bIdunno\b/gi, replacement: "I do not know" },
  { pattern: /\bkinda\b/gi, replacement: "kind of" },
  { pattern: /\blemme\b/gi, replacement: "let me" },
  { pattern: /\blet's\b/gi, replacement: "let us" },
  { pattern: /\bloven't\b/gi, replacement: "love not" },
  { pattern: /\bma'am\b/gi, replacement: "madam" },
  { pattern: /\bmayn't\b/gi, replacement: "may not" },
  { pattern: /\bmay've\b/gi, replacement: "may have" },
  { pattern: /\bmethinks\b/gi, replacement: "I think" },
  { pattern: /\bmightn't\b/gi, replacement: "might not" },
  { pattern: /\bmight've\b/gi, replacement: "might have" },
  { pattern: /\bmine's\b/gi, replacement: "mine is" },
  { pattern: /\bmustn't\b/gi, replacement: "must not" },
  { pattern: /\bmustn't've\b/gi, replacement: "must not have" },
  { pattern: /\bmust've\b/gi, replacement: "must have" },
  { pattern: /\bneath\b/gi, replacement: "beneath" },
  { pattern: /\bneedn't\b/gi, replacement: "need not" },
  { pattern: /\bnal\b/gi, replacement: "and all" },
  { pattern: /\bne'er\b/gi, replacement: "never" },
  { pattern: /\bno one's\b/gi, replacement: "no one is" },
  { pattern: /\bnothing's\b/gi, replacement: "nothing is" },
  { pattern: /\bo'clock\b/gi, replacement: "of the clock" },
  { pattern: /\bo'er\b/gi, replacement: "over" },
  { pattern: /\bol'\b/gi, replacement: "old" },
  { pattern: /\bought've\b/gi, replacement: "ought have" },
  { pattern: /\boughtn't\b/gi, replacement: "ought not" },
  { pattern: /\boughtn't've\b/gi, replacement: "ought not have" },
  { pattern: /\bround\b/gi, replacement: "around" },
  { pattern: /\bs\b/gi, replacement: "is" },
  { pattern: /\bshalln't\b/gi, replacement: "shall not" },
  { pattern: /\bshan'\b/gi, replacement: "shall not" },
  { pattern: /\bshan't\b/gi, replacement: "shall not" },
  { pattern: /\bshe'd\b/gi, replacement: "she had" },
  { pattern: /\bshe'll\b/gi, replacement: "she will" },
  { pattern: /\bshe's\b/gi, replacement: "she is" },
  { pattern: /\bshe'd'nt've\b/gi, replacement: "she did not have" },
  { pattern: /\bshould've\b/gi, replacement: "should have" },
  { pattern: /\bshouldn't\b/gi, replacement: "should not" },
  { pattern: /\bshouldn't've\b/gi, replacement: "should not have" },
  { pattern: /\bsomebody's\b/gi, replacement: "somebody is" },
  { pattern: /\bsomeone's\b/gi, replacement: "someone is" },
  { pattern: /\bsomething's\b/gi, replacement: "something is" },
  { pattern: /\bso're\b/gi, replacement: "so are" },
  { pattern: /\bso's\b/gi, replacement: "so is" },
  { pattern: /\bso've\b/gi, replacement: "so have" },
  { pattern: /\bthat'll\b/gi, replacement: "that will" },
  { pattern: /\bthat're\b/gi, replacement: "that are" },
  { pattern: /\bthat's\b/gi, replacement: "that is" },
  { pattern: /\bthat'd\b/gi, replacement: "that had" },
  { pattern: /\bthere'd\b/gi, replacement: "there had" },
  { pattern: /\bthere'll\b/gi, replacement: "there will" },
  { pattern: /\bthere're\b/gi, replacement: "there are" },
  { pattern: /\bthere's\b/gi, replacement: "there is" },
  { pattern: /\bthese're\b/gi, replacement: "these are" },
  { pattern: /\bthese've\b/gi, replacement: "these have" },
  { pattern: /\bthey'd\b/gi, replacement: "they would" },
  { pattern: /\bthey'd've\b/gi, replacement: "they would have" },
  { pattern: /\bthey'll\b/gi, replacement: "they will" },
  { pattern: /\bthey're\b/gi, replacement: "they are" },
  { pattern: /\bthey've\b/gi, replacement: "they have" },
  { pattern: /\bthis's\b/gi, replacement: "this is" },
  { pattern: /\bthose're\b/gi, replacement: "those are" },
  { pattern: /\bthose've\b/gi, replacement: "those have" },
  { pattern: /\bthout\b/gi, replacement: "without" },
  { pattern: /\btil\b/gi, replacement: "until" },
  { pattern: /\btis\b/gi, replacement: "it is" },
  { pattern: /\bto've\b/gi, replacement: "to have" },
  { pattern: /\btryna\b/gi, replacement: "trying to" },
  { pattern: /\btwas\b/gi, replacement: "it was" },
  { pattern: /\btween\b/gi, replacement: "between" },
  { pattern: /\btwere\b/gi, replacement: "it were" },
  { pattern: /\bw'all\b/gi, replacement: "we all" },
  { pattern: /\bw'at\b/gi, replacement: "we at" },
  { pattern: /\bwanna\b/gi, replacement: "want to" },
  { pattern: /\bwasn't\b/gi, replacement: "was not" },
  { pattern: /\bwe'd\b/gi, replacement: "we had" },
  { pattern: /\bwe'd've\b/gi, replacement: "we would have" },
  { pattern: /\bwe'll\b/gi, replacement: "we will" },
  { pattern: /\bwe're\b/gi, replacement: "we are" },
  { pattern: /\bwe've\b/gi, replacement: "we have" },
  { pattern: /\bweren't\b/gi, replacement: "were not" },
  { pattern: /\bwhatcha\b/gi, replacement: "what are you" },
  { pattern: /\bwhatchy'all\b/gi, replacement: "what do you all" },
  { pattern: /\bwhat'd\b/gi, replacement: "what did" },
  { pattern: /\bwhat'll\b/gi, replacement: "what will" },
  { pattern: /\bwhat're\b/gi, replacement: "what are" },
  { pattern: /\bwhat's\b/gi, replacement: "what is" },
  { pattern: /\bwhat've\b/gi, replacement: "what have" },
  { pattern: /\bwhen'd\b/gi, replacement: "when did" },
  { pattern: /\bwhen's\b/gi, replacement: "when has" },
  { pattern: /\bwhere'd\b/gi, replacement: "where did" },
  { pattern: /\bwhere'll\b/gi, replacement: "where will" },
  { pattern: /\bwhere're\b/gi, replacement: "where are" },
  { pattern: /\bwhere's\b/gi, replacement: "where is" },
  { pattern: /\bwhere've\b/gi, replacement: "where have" },
  { pattern: /\bwhich'd\b/gi, replacement: "which would" },
  { pattern: /\bwhich'll\b/gi, replacement: "which will" },
  { pattern: /\bwhich're\b/gi, replacement: "which are" },
  { pattern: /\bwhich's\b/gi, replacement: "which has" },
  { pattern: /\bwhich've\b/gi, replacement: "which have" },
  { pattern: /\bwho'd\b/gi, replacement: "who had" },
  { pattern: /\bwho'd've\b/gi, replacement: "who would have" },
  { pattern: /\bwho'll\b/gi, replacement: "who shall" },
  { pattern: /\bwho're\b/gi, replacement: "who are" },
  { pattern: /\bwho's\b/gi, replacement: "who is" },
  { pattern: /\bwho've\b/gi, replacement: "who have" },
  { pattern: /\bwhy'd\b/gi, replacement: "why did" },
  { pattern: /\bwhy'dja\b/gi, replacement: "why did you" },
  { pattern: /\bwhy're\b/gi, replacement: "why are" },
  { pattern: /\bwhy's\b/gi, replacement: "why is" },
  { pattern: /\bwilln't\b/gi, replacement: "will not" },
  { pattern: /\bwon't\b/gi, replacement: "will not" },
  { pattern: /\bwonnot\b/gi, replacement: "will not" },
  { pattern: /\bwould've\b/gi, replacement: "would have" },
  { pattern: /\bwouldn't\b/gi, replacement: "would not" },
  { pattern: /\bwouldn't've\b/gi, replacement: "would not have" },
  { pattern: /\by'ain't\b/gi, replacement: "you are not" },
  { pattern: /\by'all\b/gi, replacement: "you all" },
  { pattern: /\by'all'd've\b/gi, replacement: "you all would have" },
  { pattern: /\by'all'dn't've\b/gi, replacement: "you all would not have" },
  { pattern: /\by'all're\b/gi, replacement: "you all are" },
  { pattern: /\by'all'ren't\b/gi, replacement: "you all are not " },
  { pattern: /\by’all’d’nt’ve’d’d’I’d’nt’ve’d’y’all’t’ve’d\b/gi, replacement: "you all would not have had had I had not have had you all to have had" },
  { pattern: /\by'at\b/gi, replacement: "you at" },
  { pattern: /\byes'm\b/gi, replacement: "yes madam" },
  { pattern: /\by'ever\b/gi, replacement: "have you ever" },
  { pattern: /\by'know\b/gi, replacement: "you know" },
  { pattern: /\byessir\b/gi, replacement: "yes sir" },
  { pattern: /\byou'd\b/gi, replacement: "you would" },
  { pattern: /\byou'dn't've\b/gi, replacement: "you would not have" },
  { pattern: /\byou'll\b/gi, replacement: "you will" },
  { pattern: /\byou're\b/gi, replacement: "you are" },
  { pattern: /\byou've\b/gi, replacement: "you have" }
];
