let obheavydict = {
  //General vocabulary
  "a beer": "coldie",
  "a good idea": "good oil",
  "a look": "a squiz",
  "a lot": "heaps",
  "a problem": "beef",
  "above average": "gun",
  "absolutly true": "fair dinkum",
  "aggravated": "aggro",
  "aggravation": "aggro",
  "agressive": "aggro",
  "aluminum foil": "al-foil",
  "ambulance": "ambo",
  "an idiot": "a ning-nong",
  "angred": "crook",
  "anxious": "toey",
  "appartment": "unit",
  "arrive": "rock up",
  "arrived": "rocked up",
  "as fast as possible": "flat out",
  "as if": "'sif",
  "astounded": "gobsmacked",
  "bachalor's party": "buck's night",
  "bad luck": "stiff bickies",
  "bad weather": "dirty",
  "barbecue": "barbie",
  "basic": "bog standard",
  "be lazy": "bludge",
  "beat up": "flog",
  "become obsolete": "drum",
  "beer": "coldie",
  "beers": "coldies",
  "believe": "reckon",
  "believed": "reckon'd",
  "best in class": "dux",
  "bic lighter": "bickie",
  "bill": "docket",
  "biscuit": "bickie",
  "boast": "big-note",
  "box wine": "goon",
  "brag": "big-note",
  "break": "cark it",
  "broke": "carked it",
  "broken": "buggered:4||bung",
  "bucking oath": "ken oath",
  "bucking ugly": "fugly",
  "buisness": "bizz",
  "buisy": "flat out",
  "bungie cord": "occy strap",
  "can of beer": "tinny",
  "cattle rustler": "cattle duffer",
  "certain": "dead set",
  "chattering": "earbashing",
  "cheating": "rort",
  "cheep looking": "povo",
  "cheep wine": "goon",
  "chicken": "chook",
  "clothes line": "hills hoist",
  "clumsy": "unco",
  "cockatoo": "cockie",
  "come on": "carn",
  "coming down": "jaded",
  "complain": "whinge",
  "complained": "whinged",
  "complaining": "whinging",
  "completely loyal": "true blue",
  "condom": "dinger",
  "cork": "bung",
  "criticise": "knock",
  "darling": "darl",
  "dead": "cactus",
  "dead": "carked it",
  "defrauding": "rort",
  "delighted": "rapt",
  "designated driver": "deso",
  "devastated": "devo",
  "deviant": "devo",
  "dialect": "lingo",
  "die": "cark it",
  "disgusting": "feral",
  "dishonest": "shonky",
  "do not care": "not arsed",
  "documentary": "doco",
  "door screen": "fly wire",
  "dork": "dag",
  "dorky": "daggy",
  "drunk": "cooked",
  "dubious": "shonky",
  "duh": "der",
  "duvet": "doona",
  "earn a living": "make a quid",
  "easy job": "piece of piss",
  "easy task": "piece of piss",
  "eat": "bog in",
  "electoral district": "division",
  "evening": "evo",
  "everything is all right": "she's apples",
  "everything will be all right": "she'll be apples",
  "exausted": "knackered",
  "excellent": "ace:5||deadly",
  "extreemly drunk": "ratshit",
  "extremely wet": "satched",
  "fantastic": "beaut",
  "farmer": "cockie",
  "fed up with": "get jack of",
  "feeling broody": "clucky",
  "feeling maternal": "clucky",
  "fiddling": "rort",
  "figure out": "sus",
  "figured out": "sused",
  "firefighter": "firey",
  "flat": "unit",
  "flu": "wog",
  "fool": "drongo",
  "foolish": "drongo",
  "forest fire": "brushfire",
  "fucking oath": "ken oath",
  "fucking ugly": "fugly",
  "full of shit": "showbag",
  "gas station": "servo",
  "gather": "muster",
  "denigrate": "hang shit",
  "genuine": "dinkum",
  "get drunk": "get crunk",
  "get fired": "get the pink slip",
  "get lost": "piss off",
  "get out of here": "rack off",
  "get rid of": "flick",
  "get upset": "spit the dummy",
  "gift": "prezzy",
  "give it a go": "give it a burl",
  "go on": "garn",
  "going": "garn",
  "good day": "g'day",
  "good example": "pearler",
  "good for you": "good onya",
  "good on you": "onya",
  "got fired": "got the pink slip",
  "great": "beaut:6||grouse",
  "had an accident": "come a guster",
  "hammer out": "nut out",
  "have a go": "give it a burl",
  "have an accident": "come a guster",
  "he is not bright": "they're not the full quid",
  "hiking": "brushwalking",
  "homeless person": "derro",
  "honest": "dinkum",
  "horny": "toey",
  "hot water bottle": "hottie",
  "how are you doing": "how ya gahn",
  "how have you been": "how ya gahn",
  "I don't see a problem with that": "fair enough",
  "idiot": "derro",
  "in trouble": "buggered",
  "indisputable": "dead set",
  "inebriated": "munted",
  "inform about": "dob",
  "inform on": "dob",
  "information": "drum",
  "inspect": "dekko",
  "jaded": "jaded",
  "jinx": "moz",
  "keroscene": "kero",
  "keyed up": "toey",
  "kindergarten": "kindie",
  "klutz": "unco",
  "language": "lingo",
  "lipstick": "lippy",
  "look at": "dekko",
  "lottery ticket": "scratchie",
  "low quality": "shonky",
  "made a bad mistake": "come a guster",
  "make a bad mistake": "come a guster",
  "mangled": "munted",
  "miniscule ammount": "poofteenth",
  "mock": "hang shit",
  "mosquieto": "mozzie",
  "nagging": "earbashing",
  "nervous": "toey",
  "no": "nah",
  "no!": "yeah, nah!",
  "no problem": "no worries",
  "non-functional": "cactus",
  "nose around": "stickybeak",
  "not functioning": "cactus",
  "not intrested": "not arsed",
  "not working": "bung",
  "obsoless": "drum",
  "OK": "fair enough",
  "okay": "fair enough",
  "on edge": "toey",
  "out of controll": "feral",
  "outraged": "spit the dummy",
  "pants": "dacks",
  "pary": "rage",
  "passifier": "dummy",
  "pathway": "footpath",
  "paved road": "sealed road",
  "perfectly suited": "duck's guts",
  "pervert": "perv",
  "petrol station": "servo",
  "plain": "bog standard",
  "play hookie": "wag",
  "pleasing": "stellar",
  "pony": "brumbie",
  "poorly made": "shonky",
  "pregnant": "preggo",
  "present": "prezzy",
  "prospect": "fossick",
  "push off": "rack off",
  "quilt": "doona",
  "real": "dinkum",
  "receipt": "docket",
  "reserve": "bags",
  "reserved": "baged",
  "rotten": "feral",
  "round up": "muster",
  "sandwich": "sanga",
  "scamming": "rort",
  "secondhand store": "op shop",
  "sell": "flog",
  "service station": "servo",
  "she is not bright": "they're not the full quid",
  "shirk": "bludge",
  "shorts": "dacks",
  "sick": "crook",
  "sideboard": "duchess",
  "sidewalk": "footpath",
  "skip out": "wag",
  "skip school": "wag",
  "skip work": "wag",
  "slander": "hang shit",
  "sleeping bag": "matilda",
  "sleeping roll": "matilda",
  "smidge": "poofteenth",
  "smidgen": "poofteenth",
  "smoker": "buttsucker",
  "snitch": "dob",
  "stag party": "buck's night",
  "steal": "flog",
  "stopper": "bung",
  "street musician": "busker",
  "stupid": "derro",
  "sully": "hang shit",
  "sunbathe": "sunbake",
  "suprised": "gobsmacked",
  "suspect": "sus",
  "suspected": "sused",
  "suspicious": "sus",
  "swim trunks": "boardies",
  "talented": "shit-hot",
  "talk a lot": "yabber",
  "talking a lot": "yabbering",
  "terrific": "beaut",
  "terrific": "grouse",
  "thank you": "ta",
  "thanks": "stellar",
  "that is all right": "no worries",
  "that is correct": "too right",
  "that is easy": "piece of piss",
  "that is great": "the cat's pyjamas",
  "that's certainly true": "bloody oath",
  "that's obvious": "der",
  "the best of its kind": "dux",
  "the real thing": "dinky-di",
  "the truth": "good oil",
  "they are not bright": "they're not the full quid",
  "think": "reckon",
  "thought": "reckon'd",
  "thrift store": "op shop",
  "thrifty": "tight",
  "tired": "buggered",
  "toilet": "dunny",
  "top of the class": "dux",
  "tough luck": "stiff cheddar",
  "trashy": "feral",
  "treat roughly": "flog",
  "trousers": "dacks",
  "try it": "give it a burl",
  "turn up": "rock up",
  "turned up": "rocked up",
  "unadorned": "bog standard",
  "uncool": "daggy",
  "uncoordinated": "unco",
  "uncover": "sus",
  "uncovered": "sused",
  "underhanded": "shonky",
  "underwear": "dacks",
  "unfair": "crook",
  "unfashionable": "daggy",
  "unhygenic": "feral",
  "university": "uni",
  "upset": "cut",
  "useful information": "good oil",
  "vegetables": "veggies",
  "very": "bloody",
  "very angry": "ropeable",
  "very drunk": "ratshit",
  "very easy": "piece of piss",
  "very good": "ace:6||grouse||heaps good||sick:3",
  "very happy": "rapt",
  "very pleased": "stoked",
  "very tired": "knackered",
  "vomit": "spew",
  "walkway": "footpath",
  "waste time": "bludge",
  "weather is bad": "dirty",
  "weather will be bad": "dirty",
  "well done": "good onya",
  "will not be intrested": "ain't arsed",
  "window screen": "fly wire",
  "woman": "sheila",
  "woodland": "brushland",
  "woods": "brush",
  "workers comp": "compo",
  "workers compensation": "compo",
  "yes!": "nah, yea!",
  "you are welcome": "no worries",
  "how are you": "how ya goin",
  "good evening": "Evening",

  // Acknowledgements
  "thanks": "cheers",
  "thank you": "ta",
  "you're welcome": "too right",
  "okay": "no wucka’s",
  "yes": "yea",
  "no": "nup",
  "to": "ta",

  // People
  "friend": "mate",
  "friends": "mob",
  "pony": "hoofface",
  "stallion": "bloke",
  "mare": "sheila",
  "colt": "ankle biter",
  "foal": "shark biscuit",

  // Food & Drink
  "food": "tucker",
  "drink": "coldie",
  "barbecue": "barbie bash",
  "breakfast": "brekky",
  "sandwich": "sanger",
  "sausage": "snag",
  "beer": "tinny",

  // Time & Place
  "afternoon": "s’arvo",
  "evening": "s’eve’n",
  "morning": "blinkin’ dawn",
  "bathroom": "thunderbox",
  "toilet": "dunny",
  "home": "swag heap",
  "countryside": "arse-end of the bush",
  "nowhere": "woop woop",

  // Emotions & States
  "tired": "buggered",
  "excited": "frothin’",
  "happy": "rapt",
  "sad": "devo as hell",
  "angry": "crackin’ the shits",
  "sick": "crook as a dog",
  "love": "mad for ya",
  "affection": "mushy stuff",
  "joy": "a real hoot",
  "fear": "gutful of dread",
  "anxiety": "buzzin’ too hard",
  "pride": "walkin’ tall",

  // Military Terms
  "orders": "marchin’ words",
  "report": "sitrep",
  "mission": "op",
  "command": "top brass",
  "commander": "the big bugger",
  "troops": "mob",
  "objective": "the thing to nick",
  "enemy": "tossers",
  "squad": "my lot",
  "recon": "sneaky peek",

  // MLP Lore
  "cutie mark": "arse badge",
  "princess": "shiny-head",
  "pegasus": "wingnut",
  "unicorn": "pointy",
  "earth pony": "mudhoover",
  "changeling": "bugger-shifter",
  "griffon": "clawface",
  "alicorn": "shiny-hybrid",
  "equestria": "the sunspot",
  "canterlot": "Cannylot",
  "ponyville": "Podunkville",
  "crystal empire": "shiny hole up north",

  // Sentence-level transforms
  "i do not know": "dunno, mate",
  "i am going to": "i’m gonna leg it",
  "i do not want to": "don’t fancy it",
  "we have to go": "we gotta hoof it",
  "are you okay": "ya crook or what?",
  "what is going on": "what’s the bloody story?",
  "this is very important": "this is bloody huge",
  "that is not my problem": "not my paddock, not my dung heap",

  //Grammer tweaks
  "and": "an",
  "into": "inna",
  "I am a": "imma",
  "onto": "onna",
  "off of": "offa",
  "i had": "idda",
  "i would": "idda",
  "sister": "sis",
  "brother": "bro",
  "mom": "mum",
  "dad": "da"
}

let obheavyregex = [
  { pattern: /\bgoing to\b/gi, replacement: "gonna" },
  { pattern: /\bwant to\b/gi, replacement: "wanna" },
  { pattern: /\bgive me\b/gi, replacement: "gimme" },
  { pattern: /\bgot to\b/gi, replacement: "gotta" },
  { pattern: /ing\b/g, replacement: "in’" },
  { pattern: /\byour\b/gi, replacement: "ya" },
  { pattern: /balright\b/gi, replacement: "a'ight" },
  { pattern: /band\b/gi, replacement: "n" },
  { pattern: /bare not you\b/gi, replacement: "arencha" },
  { pattern: /baren't you\b/gi, replacement: "arencha" },
  { pattern: /bare not\b/gi, replacement: "aren't" },
  { pattern: /babout\b/gi, replacement: "bout" },
  { pattern: /bcannot\b/gi, replacement: "can't" },
  { pattern: /bcaptain\b/gi, replacement: "cap'n" },
  { pattern: /bbecause\b/gi, replacement: "cuz" },
  { pattern: /bcome on\b/gi, replacement: "c'mon" },
  { pattern: /bcould have\b/gi, replacement: "could've" },
  { pattern: /bcould not\b/gi, replacement: "couldn't" },
  { pattern: /bcould not have\b/gi, replacement: "couldn't've" },
  { pattern: /bcup of\b/gi, replacement: "cuppa" },
  { pattern: /bdid not\b/gi, replacement: "didn't" },
  { pattern: /bdoes not\b/gi, replacement: "doesn't" },
  { pattern: /bdo not\b/gi, replacement: "don't" },
  { pattern: /bdoes not\b/gi, replacement: "don't" },
  { pattern: /bdo not know\b/gi, replacement: "dunno" },
  { pattern: /bdon't know\b/gi, replacement: "dunno" },
  { pattern: /bdo you\b/gi, replacement: "d'ya" },
  { pattern: /bdid you\b/gi, replacement: "d'ya" },
  { pattern: /beven\b/gi, replacement: "e'en" },
  { pattern: /bever\b/gi, replacement: "e'er" },
  { pattern: /bthem\b/gi, replacement: "em" },
  { pattern: /beverybody has\b/gi, replacement: "everybody's" },
  { pattern: /beverybody is\b/gi, replacement: "everybody's" },
  { pattern: /beveryone has\b/gi, replacement: "everyone's" },
  { pattern: /beveryone is\b/gi, replacement: "everyone's" },
  { pattern: /beverything has\b/gi, replacement: "everything's" },
  { pattern: /beverything is\b/gi, replacement: "everything's" },
  { pattern: /bfixing to\b/gi, replacement: "finna" },
  { pattern: /bagainst\b/gi, replacement: "gainst" },
  { pattern: /bgood day\b/gi, replacement: "g'day" },
  { pattern: /bgive me\b/gi, replacement: "gimme" },
  { pattern: /bgiven\b/gi, replacement: "giv'n" },
  { pattern: /bgive us\b/gi, replacement: "gi'z" },
  { pattern: /bgoing to\b/gi, replacement: "gonna" },
  { pattern: /bgot to\b/gi, replacement: "gotta" },
  { pattern: /bhad not\b/gi, replacement: "hadn't" },
  { pattern: /bhad have\b/gi, replacement: "had've" },
  { pattern: /bhas not\b/gi, replacement: "hasn't" },
  { pattern: /bhave not\b/gi, replacement: "haven't" },
  { pattern: /bhe had\b/gi, replacement: "he'd" },
  { pattern: /bhe would\b/gi, replacement: "he'd" },
  { pattern: /bhe shall\b/gi, replacement: "he'll" },
  { pattern: /bhe will\b/gi, replacement: "he'll" },
  { pattern: /bhe has\b/gi, replacement: "he's" },
  { pattern: /bhe is\b/gi, replacement: "he's" },
  { pattern: /bhere is\b/gi, replacement: "here's" },
  { pattern: /bhow did\b/gi, replacement: "how'd" },
  { pattern: /bhow would\b/gi, replacement: "how'd" },
  { pattern: /bhow will\b/gi, replacement: "how'll" },
  { pattern: /bhow shall\b/gi, replacement: "how'll" },
  { pattern: /bhow are\b/gi, replacement: "how're" },
  { pattern: /bhow has\b/gi, replacement: "how's" },
  { pattern: /bhow is\b/gi, replacement: "how's" },
  { pattern: /bhow does\b/gi, replacement: "how's" },
  { pattern: /bI had\b/gi, replacement: "I'd" },
  { pattern: /bI would\b/gi, replacement: "I'd" },
  { pattern: /bI shall\b/gi, replacement: "I'll" },
  { pattern: /bI will\b/gi, replacement: "I'll" },
  { pattern: /bI am\b/gi, replacement: "I'm" },
  { pattern: /bI am about to\b/gi, replacement: "Imma" },
  { pattern: /bI am going to\b/gi, replacement: "Imma" },
  { pattern: /bisn't it\b/gi, replacement: "innit" },
  { pattern: /bain't it\b/gi, replacement: "innit" },
  { pattern: /bit would\b/gi, replacement: "it'd" },
  { pattern: /bit shall\b/gi, replacement: "it'll" },
  { pattern: /bit will\b/gi, replacement: "it'll" },
  { pattern: /bit has\b/gi, replacement: "it's" },
  { pattern: /bit is\b/gi, replacement: "it's" },
  { pattern: /bI do not know\b/gi, replacement: "Idunno" },
  { pattern: /bkind of\b/gi, replacement: "kinda" },
  { pattern: /blet me\b/gi, replacement: "lemme" },
  { pattern: /blet us\b/gi, replacement: "let's" },
  { pattern: /bmadam\b/gi, replacement: "ma'am" },
  { pattern: /bno one has\b/gi, replacement: "no one's" },
  { pattern: /bno one is\b/gi, replacement: "no one's" },
  { pattern: /bnothing has\b/gi, replacement: "nothing's" },
  { pattern: /bnothing is\b/gi, replacement: "nothing's" },
  { pattern: /bof the clock\b/gi, replacement: "o'clock" },
  { pattern: /bover\b/gi, replacement: "o'er" },
  { pattern: /bold\b/gi, replacement: "ol'" },
  { pattern: /baround\b/gi, replacement: "round" },
  { pattern: /bshe had\b/gi, replacement: "she'd" },
  { pattern: /bshe would\b/gi, replacement: "she'd" },
  { pattern: /bshe shall\b/gi, replacement: "she'll" },
  { pattern: /bshe will\b/gi, replacement: "she'll" },
  { pattern: /bshe has\b/gi, replacement: "she's" },
  { pattern: /bshe is\b/gi, replacement: "she's" },
  { pattern: /bshould have\b/gi, replacement: "should've" },
  { pattern: /bshould not\b/gi, replacement: "shouldn't" },
  { pattern: /bshould not have\b/gi, replacement: "shouldn't've" },
  { pattern: /bsomebody has\b/gi, replacement: "somebody's" },
  { pattern: /bsomebody is\b/gi, replacement: "somebody's" },
  { pattern: /bsomeone has\b/gi, replacement: "someone's" },
  { pattern: /bsomeone is\b/gi, replacement: "someone's" },
  { pattern: /bsomething has\b/gi, replacement: "something's" },
  { pattern: /bsomething is\b/gi, replacement: "something's" },
  { pattern: /bthat shall\b/gi, replacement: "that'll" },
  { pattern: /bthat will\b/gi, replacement: "that'll" },
  { pattern: /bthat has\b/gi, replacement: "that's" },
  { pattern: /bthat is\b/gi, replacement: "that's" },
  { pattern: /bthat would\b/gi, replacement: "that'd" },
  { pattern: /bthat had\b/gi, replacement: "that'd" },
  { pattern: /bthere had\b/gi, replacement: "there'd" },
  { pattern: /bthere would\b/gi, replacement: "there'd" },
  { pattern: /bthere shall\b/gi, replacement: "there'll" },
  { pattern: /bthere will\b/gi, replacement: "there'll" },
  { pattern: /bthere are\b/gi, replacement: "there're" },
  { pattern: /bthere has\b/gi, replacement: "there's" },
  { pattern: /bthere is\b/gi, replacement: "there's" },
  { pattern: /bthey had\b/gi, replacement: "they'd" },
  { pattern: /bthey would\b/gi, replacement: "they'd" },
  { pattern: /bthey would have\b/gi, replacement: "they'd've" },
  { pattern: /bthey could have\b/gi, replacement: "they'd've" },
  { pattern: /bthey should have\b/gi, replacement: "they'd've" },
  { pattern: /bthey shall\b/gi, replacement: "they'll" },
  { pattern: /bthey will\b/gi, replacement: "they'll" },
  { pattern: /bthey are\b/gi, replacement: "they're" },
  { pattern: /bthey were\b/gi, replacement: "they're" },
  { pattern: /bthey have\b/gi, replacement: "they've" },
  { pattern: /bthis has\b/gi, replacement: "this's" },
  { pattern: /bthis is\b/gi, replacement: "this's" },
  { pattern: /bthose are\b/gi, replacement: "those're" },
  { pattern: /bthose have\b/gi, replacement: "those've" },
  { pattern: /bwithout\b/gi, replacement: "thout" },
  { pattern: /btrying to\b/gi, replacement: "tryna" },
  { pattern: /bwant to\b/gi, replacement: "wanna" },
  { pattern: /bwas not\b/gi, replacement: "wasn't" },
  { pattern: /bwe had\b/gi, replacement: "we'd" },
  { pattern: /bwe would\b/gi, replacement: "we'd" },
  { pattern: /bwe did\b/gi, replacement: "we'd" },
  { pattern: /bwe would have\b/gi, replacement: "we'd've" },
  { pattern: /bwe shall\b/gi, replacement: "we'll" },
  { pattern: /bwe will\b/gi, replacement: "we'll" },
  { pattern: /bwe are\b/gi, replacement: "we're" },
  { pattern: /bwe have\b/gi, replacement: "we've" },
  { pattern: /bwere not\b/gi, replacement: "weren't" },
  { pattern: /bwhat are you\b/gi, replacement: "whatcha" },
  { pattern: /bwhat did\b/gi, replacement: "what'd" },
  { pattern: /bwhat shall\b/gi, replacement: "what'll" },
  { pattern: /bwhat will\b/gi, replacement: "what'll" },
  { pattern: /bwhat are\b/gi, replacement: "what're" },
  { pattern: /bwhat were\b/gi, replacement: "what're" },
  { pattern: /bwhat has\b/gi, replacement: "what's" },
  { pattern: /bwhat is\b/gi, replacement: "what's" },
  { pattern: /bwhat does\b/gi, replacement: "what's" },
  { pattern: /bwhat have\b/gi, replacement: "what've" },
  { pattern: /bwhen did\b/gi, replacement: "when'd" },
  { pattern: /bwhen has\b/gi, replacement: "when's" },
  { pattern: /bwhen is\b/gi, replacement: "when's" },
  { pattern: /bwhere did\b/gi, replacement: "where'd" },
  { pattern: /bwhere shall\b/gi, replacement: "where'll" },
  { pattern: /bwhere will\b/gi, replacement: "where'll" },
  { pattern: /bwhere are\b/gi, replacement: "where're" },
  { pattern: /bwhere has\b/gi, replacement: "where's" },
  { pattern: /bwhere is\b/gi, replacement: "where's" },
  { pattern: /bwhere does\b/gi, replacement: "where's" },
  { pattern: /bwhere have\b/gi, replacement: "where've" },
  { pattern: /bwhich shall\b/gi, replacement: "which'll" },
  { pattern: /bwhich will\b/gi, replacement: "which'll" },
  { pattern: /bwhich are\b/gi, replacement: "which're" },
  { pattern: /bwhich has\b/gi, replacement: "which's" },
  { pattern: /bwhich is\b/gi, replacement: "which's" },
  { pattern: /bwhich have\b/gi, replacement: "which've" },
  { pattern: /bwho would\b/gi, replacement: "who'd" },
  { pattern: /bwho had\b/gi, replacement: "who'd" },
  { pattern: /bwho did\b/gi, replacement: "who'd" },
  { pattern: /bwho shall\b/gi, replacement: "who'll" },
  { pattern: /bwho will\b/gi, replacement: "who'll" },
  { pattern: /bwho are\b/gi, replacement: "who're" },
  { pattern: /bwho has\b/gi, replacement: "who's" },
  { pattern: /bwho is\b/gi, replacement: "who's" },
  { pattern: /bwho does\b/gi, replacement: "who's" },
  { pattern: /bwho have\b/gi, replacement: "who've" },
  { pattern: /bwhy did\b/gi, replacement: "why'd" },
  { pattern: /bwhy did you\b/gi, replacement: "why'dja" },
  { pattern: /bwhy are\b/gi, replacement: "why're" },
  { pattern: /bwhy has\b/gi, replacement: "why's" },
  { pattern: /bwhy is\b/gi, replacement: "why's" },
  { pattern: /bwhy does\b/gi, replacement: "why's" },
  { pattern: /bwill not\b/gi, replacement: "won't" },
  { pattern: /bwould have\b/gi, replacement: "would've" },
  { pattern: /bwould not\b/gi, replacement: "wouldn't" },
  { pattern: /bhave you ever\b/gi, replacement: "y'ever" },
  { pattern: /byou know\b/gi, replacement: "y'know" },
  { pattern: /byes sir\b/gi, replacement: "yessir" },
  { pattern: /byou had\b/gi, replacement: "you'd" },
  { pattern: /byou would\b/gi, replacement: "you'd" },
  { pattern: /byou would not have\b/gi, replacement: "you'dn't've" },
  { pattern: /byou wouldn't have\b/gi, replacement: "you'dn't've" },
  { pattern: /byou shall\b/gi, replacement: "you'll" },
  { pattern: /byou will\b/gi, replacement: "you'll" },
  { pattern: /byou are\b/gi, replacement: "you're" },
  { pattern: /byou have\b/gi, replacement: "you've" }

]
