let oldenglishdict = {
  // Core function words
  "yes": "yea",
  "no": "nay",
  "maybe": "it may be so",
  "very": "full",
  "really": "truly",
  "according to": "after",
  "adorn": "dighte",
  "advice": "conseil:5||rede",
  "again": "eft",
  "against": "agayn",
  "ago": "agon",
  "agreement": "forward",
  "alike": "yliche",
  "also": "eke",
  "although": "al",
  "anywhere": "owher",
  "arrangement": "array",
  "as": "als||al so",
  "ask": "axe",
  "at": "at",
  "at first": "erst",
  "at once": "atones",
  "at the": "atte",
  "be called": "highte",
  "because": "for:5||for that:2||forwhy",
  "befall": "fallen:8||fil:3||yfalle",
  "before": "er:6||biforn",
  "between": "bitwix||bitwinen",
  "bird": "fowel",
  "bit": "deel",
  "burn": "brenne",
  "burst": "bresten:4||braste:3||ybrest",
  "by necessity": "nedes",
  "call": "clepen",
  "certain": "certeyn:7||siker",
  "certainly": "certes",
  "choose": "chesen:4||chees3||ychose",
  "churlishness": "vilenye",
  "condition": "array",
  "consider": "deme:4||wene",
  "counsel": "conseil",
  "courteous": "hende",
  "crazy": "wode",
  "cure": "heelp",
  "dear": "leef",
  "desire": "lust:6||wilnen",
  "despite": "maugree",
  "destruction": "bane",
  "device": "devyse",
  "direct": "gyen",
  "doubt": "drede",
  "each": "ech:8||iche||everich:4||ilk",
  "earlier": "er",
  "endure": "duren",
  "equip": "dighte",
  "ere": "er",
  "even if": "al",
  "ever": "ay",
  "every one": "everichon",
  "everywhere": "overal",
  "example": "ensample",
  "expedition": "viage",
  "far": "fer",
  "farther": "ferrer",
  "farthest": "ferrest",
  "fear": "drede",
  "first": "erst",
  "food": "mete",
  "forever": "ay",
  "formerly": "whilom",
  "from": "at||fro:3",
  "give": "yiven:6||yaf||yeven",
  "glad": "feyn",
  "graceful": "fetis",
  "guide": "gyen",
  "handy": "hende",
  "happen": "fallen:8||fel:3||yfalle",
  "hardly": "unethe",
  "hateful": "looth",
  "help, ": "helpen",
  "high": "heigh",
  "immediately": "atones",
  "in order to": "for to",
  "joke": "jape",
  "judge": "deme",
  "killer": "bane",
  "know": "witen:5||wot||wiste:2",
  "last": "duren",
  "limb": "lym",
  "loath": "looth",
  "long ago": "agon",
  "lose": "lesen",
  "mad": "wode",
  "marry": "wedden",
  "near": "ny",
  "nearer": "near",
  "nearest": "next",
  "noble": "gentle",
  "Of": "at",
  "once": "ones",
  "once": "whilom",
  "or": "other",
  "pace": "paas",
  "part": "deel",
  "pity": "routh",
  "pleasure": "lust",
  "pledge": "wedden",
  "poor": "povre",
  "prepare": "dighten",
  "quickly": "blyve",
  "rank": "degree:3||estaat",
  "reckon": "rekne",
  "remedy": "boote",
  "run": "rennen:2||ran:5||yronne",
  "since": "syn||sithe:4",
  "slow walk": "paas",
  "some": "swich",
  "such": "swich",
  "suppose": "wene",
  "sure": "certeyn",
  "that same": "thilke",
  "the same": "thilke",
  "therefore": "forthy",
  "through": "thurgh",
  "to reckon": "reknen",
  "toward": "agaynes||til:4",
  "towards": "agayns",
  "trick": "devyse:6||sleighte:2||jape",
  "tricky": "hende",
  "truly": "certes",
  "trusty": "siker",
  "truth": "sooth",
  "upon": "up",
  "voyage": "viage",
  "want": "wilnen",
  "war": "werre",
  "well made": "fetis",
  "where": "there",
  "where": "ther",
  "whether": "wher",
  "willing": "feyn",
  "within": "inwith",
  "without": "withouten",
  "yonder": "yond",
  "true": "verray",
  "you": "thou",
  "your": "thine",

  // Verbs & states
  "think": "reckon",
  "understand": "grasp",
  "know": "wot",
  "believe": "hold",
  "want": "wish",
  "need": "have need of",
  "try": "seek",

  // Abstract → concrete bias
  "problem": "trouble",
  "idea": "thought",
  "reason": "cause",
  "future": "days yet to come",
  "past": "days gone",
  "danger": "peril",
  "between": "betwix",
  "long ago": "agon",

  // People
  "friend": "frīend",
  "enemy": "foe",
  "leader": "ring-giver",
  "king": "cyning",
  "queen": "cwēn",

  // Time & place
  "now": "this while",
  "soon": "ere long",
  "later": "after this",
  "here": "in this stead",
  "there": "in that stead",

  // Stock phrases
  "i do not know": "I wot not",
  "i don't know": "I wot not",
  "i understand": "I grasp thy meaning",
  "i do not understand": "I grasp it not",
  "what is going on": "what here unfolds",
  "are you okay": "art thou whole?",
  "this is important": "this bears great weight",
  "be careful": "take heed",
  "why my": "that my"
}

let oldenglishregex = [
  // Normalize contractions (after quote normalization)
  { pattern: /\bcan't\b/gi, replacement: "cannot" },
  { pattern: /\bdon't\b/gi, replacement: "do not" },
  { pattern: /\bdidn't\b/gi, replacement: "did not" },
  { pattern: /\bwon't\b/gi, replacement: "will not" },
  { pattern: /\bhadn't\b/gi, replacement: "had not" },
  { pattern: /\bi'm\b/gi, replacement: "I am" },
  { pattern: /\bit's\b/gi, replacement: "it is" },
  { pattern: /\bwouldn't\b/gi, replacement: "would not" },

  //Old English contractions
  { pattern: /\bit was\b/gi, replacement: "twas" },
  { pattern: /\bit is\b/gi, replacement: "tis" },
  { pattern: /\bit would\b/gi, replacement: "twould" },
  { pattern: /\bit will\b/gi, replacement: "twill" },
  { pattern: /\bof it\b/gi, replacement: "on’t" },


  // Negation after verb
  { pattern: /\b(do|does|did)\s+not\s+([a-z]+)/gi, replacement: "$1 $2 not" },

  // “I X not” instead of “I do not X”
  { pattern: /\bi do not (\w+)/gi, replacement: "I $1 not" },

  // Fronted objects
  { pattern: /\bI understand (.+)/gi, replacement: "$1, I grasp" },

  // Reduced auxiliaries
  { pattern: /\bgoing to\b/gi, replacement: "bound to" },
  { pattern: /\bwill\b/gi, replacement: "shall" },

  // Slight archaism without going full Luna
  { pattern: /\byour\b/gi, replacement: "thy" },
  { pattern: /\byou\b/gi, replacement: "thee" },
  { pattern: /\btheir\b/gi, replacement: "thy" },
  { pattern: /\byou\b(?=\s+(are|were|will|shall|can|may|must|do|did|have|had|know|see|think))/gi, replacement: "thou" },
  { pattern: /\byou\b/gi, replacement: "thee" },
  { pattern: /\byour\s+([bcdfghjklmnpqrstvwxyz])/gi, replacement: "thy $1" },
  { pattern: /\byour\s+([aeiou])/gi, replacement: "thine $1" },
  { pattern: /\byours\b/gi, replacement: "thine" },

  // Emphasis particles
  { pattern: /\bvery\b/gi, replacement: "full" }
]
